#version: "3.7"

#networks:
#  frontend:
  backend:

services:
    modernarchitectureshop-identityserver:
       image: modernarchitectureshop-identityserver:dev
       build:
            context: .
            dockerfile: ./src/Identity/Dockerfile
       ports:
       - "443:50000"

    modernarchitectureshop-basket:
        image: modernarchitectureshop-basketapi:dev
        build:
            context: .
            dockerfile: ./src/Basket/ModernArchitectureShop.BasketApi/Dockerfile

    modernarchitectureshop-store:
        image: modernarchitectureshop-storeapi:dev
        build:
            context: .
            dockerfile: ./src/Store/ModernArchitectureShop.StoreApi/Dockerfile

    modernarchitectureshop-blazorui:
        image: modernarchitectureshop-blazorui:dev
        build:
            context: .
            dockerfile: ./src/UI/Dockerfile
        ports:
        - "5010:5010"
